### ISSUE TITLE
typo in eda.py

### ISSUE THREAD

**Issue by Davidwang11** [UBC-MDS/Credit-Card-Default-Prediction#19]
There are two typos in eda.py

1. numeric_features = list(set(X_train.columns.tolist()), There is no X_train variable in the file, it should be train_df
2. cat_plot.save(ps.path.join(output_dir, "Distribution of categorical features by target variable.png")): ps.path should be os.path

**Comment by garhwalinauna** [comment]
Install this in the terminal
conda install -c conda-forge altair_saver

Then, import the following packages.
from altair_data_server import data_server
alt.data_transformers.enable('data_server')
alt.renderers.enable('mimetype')
from altair_saver import save

**Comment by ciciecho-ds** [comment]
Fixed! Thank you.
