### ISSUE TITLE
Minor changes in EDA

### ISSUE THREAD

**Issue by garhwalinauna** [UBC-MDS/Credit-Card-Default-Prediction#22]
Two minor things:

1. Change the file name from 'Distribution of categorical features by target variable.png' to 
'dist_categ_feats_by_target.png' or something like this. Avoid spaces and capitalize characters.
2. Add the images in the directory 'results/images/' from where James can easily integrate in the report.

**Comment by ciciecho-ds** [comment]
Updated eda.py based on these suggestions.
