### ISSUE TITLE
Minutes from Tuesday meeting

### ISSUE THREAD

**Issue by garhwalinauna** [UBC-MDS/Credit-Card-Default-Prediction#8]
Responsibilites.

Script 1 - Download data from net - **James**
Script 2 - reads the data from the first script and performs and data cleaning/pre-processing - **David**
Script 3 - exploratory data visualization(s) and table(s) - **Cici**
Script 4 - reads the data from the second script, performs some statistical or machine learning analysis and summarizes the results - **Rohit**
Script 5 - presents the key useful (not all!) exploratory data analysis as well as the statistical summaries and figures in a little report. 

flow chart/dependency diagram/ README.md - **Cici**
Software dependencies environment.yml file - **Rohit**

10+ commits, so 3 commits per person!
Communicate changes/additions/questions on Github issues
Meaningful git commits/messages (it is being marked)

_Additional task to be done._
Add References as bib file.

**Comment by jamesktkim** [comment]
I am taking on script 5

**Comment by garhwalinauna** [comment]
Done for the week.
